---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy1
  namespace: prod
  labels:
    app: v1

spec:
  replicas: 4
  selector:
    matchLabels:
      app: swiggy

  template:
    metadata:
      labels:
        app: swiggy

    spec:
      containers:
        - name: cont1
          image: manikantapaila/newrepo:bustickets
          ports:
            - containerPort: 80
